# Generated by Django 2.2.14 on 2020-08-11 08:05

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('corpsecret', models.CharField(max_length=200)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=20)),
                ('touser', models.CharField(blank=True, max_length=1000)),
                ('toparty', models.CharField(blank=True, max_length=1000)),
                ('totag', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to=upload.models.user_directory_path)),
                ('is_send', models.BooleanField(default=False)),
                ('agentid', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
